bigquery:
  datasets:
  - name: iowa_demo
    location: '{{ cookiecutter.region }}'
    create: true
    friendly_name: staging
    description: staging
    labels:
      project: 'billing'
    delete_contents_on_destroy: false
    tables:
    - name: liquor_sales
      deletion_protection: false
      view:
        query_file: defs/vw_liquor_sales.sql
        use_legacy_sql: false
    - name: liquor_sales_5_liquors_filled_days
      deletion_protection: false
      view:
        query_file: defs/vw_liquor_sales_5_liquors_filled_days.sql
        use_legacy_sql: false
