bigquery:
  datasets:
  - name: iowa_demo
    location: '{{ cookiecutter.region }}'
    create: true
    friendly_name: staging
    description: staging
    labels:
      project: 'billing'
    delete_contents_on_destroy: false
    tables:
    - name: billing_archive
      deletion_protection: false
      schema_file: defs/billing_archive.json
      time_partitioning:
        type: MONTH
        field: invoice_month
      labels:
        project: 'billing'
    - name: excluded_skus
      deletion_protection: false
      schema_file: defs/excluded_skus.json
    - name: vw_joint_master_reference
      deletion_protection: false
      view:
        query_file: defs/joint_master_query.sql
        use_legacy_sql: false
