exclude: "{{ cookiecutter.project_name }}"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-added-large-files
        args: [ '--maxkb=2048' ]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
  -   repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 2.1.5  # or specific git tag
      hooks:
        - id: forbid-binary
        - id: markdownlint # Configure in .mdlrc
        - id: script-must-have-extension
        - id: script-must-not-have-extension
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.2
    hooks:
        - id: commitizen
        - id: commitizen-branch
          stages: [push]
  -   repo: https://github.com/pycqa/isort
      rev: 5.9.3
      hooks:
      - id: isort

  -   repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1  # pick a git hash / tag to point to
      hooks:
      -   id: pydocstyle
          exclude: "generated_sql|dags"

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
      -   id: mypy
          exclude: ^(docs/|example-plugin/|dags)

  -   repo: https://github.com/pycqa/flake8
      rev: 3.9.2  # pick a git hash / tag to point to
      hooks:
      -   id: flake8
          exclude: "dags"
