kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_1"
    extraMounts:
      - hostPath: ./data
        containerPath: /tmp/data
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines/
        containerPath: /tmp/dags/pipelines
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines/../credentials
        containerPath: /tmp/credentials
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines/../metadata/
        containerPath: /tmp/dags/metadata
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines/../dbt/
        containerPath: /tmp/dags/
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_2"
    extraMounts:
      - hostPath: ./data
        containerPath: /tmp/data
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines//
        containerPath: /tmp/dags/pipelines
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines//../credentials
        containerPath: /tmp/credentials
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines//../metadata/
        containerPath: /tmp/dags/metadata
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_3"
    extraMounts:
      - hostPath: ./data
        containerPath: /tmp/data
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines//
        containerPath: /tmp/dags/pipelines
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines//../credentials
        containerPath: /tmp/credentials
      - hostPath: /Users/timellis-smith/workspace/cookiecutter-data-engineering/pipelines//../metadata/
        containerPath: /tmp/dags/metadata
